spring:
  application:
    name: product-service
  profiles:
    active: ${APP_PROFILE}
    include: kafka
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}"
vendo:
  web:
    global-exception-handler:
      enabled: false

